"""Generated by tools/make_fixtures.py; all observations and identities are synthetic."""
from copy import deepcopy
import importlib
import json
import runpy
from pathlib import Path
import sys
from types import ModuleType, SimpleNamespace

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))
from test_private_runs import state
from test_tracking_integrity import tracker
from make_fixtures import full_review_scenarios

CASE = full_review_scenarios()


@pytest.fixture
def research(state, monkeypatch):
    directory = Path(__file__).resolve().parents[2] / "docs" / "backtest-2026-06"
    monkeypatch.syspath_prepend(str(directory))
    names = ("distress_features_extract", "distress_features_fast",
             "distress_oos_validate", "distress_oos_validate2")
    for name in names:
        monkeypatch.delitem(sys.modules, name, raising=False)
    return tuple(importlib.import_module(name) for name in names)


def _synthetic_pull(row):
    return {**row, "series": deepcopy(CASE["feature"]["series"])}


@pytest.mark.parametrize("extractor", [0, 1])
def test_extractors_use_current_private_backtest_writer(research, state, monkeypatch, extractor):
    trusted, fast, older, newer = research
    backtest = importlib.import_module("backtest")
    cell = backtest._write_cell(deepcopy(CASE["panel"]))
    module = research[extractor]
    monkeypatch.setattr(module, "pull_one", _synthetic_pull)
    (module.main if extractor == 0 else module.run)()
    destination = Path(state["root"]) / "backtest-research" / "distress_features.json"
    assert trusted.features_path() == destination
    assert trusted.backtest_files() == [cell]
    rows = trusted.load_features()
    assert len(rows) == 1
    assert rows[0]["ticker"] == CASE["panel"]["names"][0]["ticker"]
    assert rows[0]["series"] == CASE["feature"]["series"]
    assert older.load_features() == rows
    calls = []
    monkeypatch.setattr(older, "load_features", lambda: calls.append(destination) or [])
    assert newer.load() == ([], 0, 0)
    assert calls == [destination]


@pytest.mark.parametrize("populated", [False, True])
def test_older_oos_cli_reads_current_private_artifact(research, state, monkeypatch, capsys, populated):
    trusted, _, older, _ = research
    destination = Path(state["root"]) / "backtest-research" / "distress_features.json"
    if populated:
        trusted.write_features(deepcopy(CASE["oos_features"]))
    else:
        assert not destination.exists()
    script = str(Path(older.__file__))
    monkeypatch.setattr(sys, "argv", [script])
    runpy.run_path(script, run_name="__main__")
    output = capsys.readouterr().out
    assert trusted.features_path() == destination
    if populated:
        assert "non-financial priceable w/ core fundamentals: n=4  blowups=2" in output
        assert "OOS AUC TEST=" in output
        assert "logistic step skipped:" not in output
        assert trusted.load_features() == CASE["oos_features"]
    else:
        assert "features file not ready: " + str(destination) in output
        assert not destination.exists()


@pytest.mark.parametrize("extractor", [0, 1])
@pytest.mark.parametrize("visibility", ["PUBLIC", None])
def test_unproved_research_destination_preserves_public_sentinel(
        research, state, monkeypatch, tmp_path, extractor, visibility):
    public = tmp_path / "synthetic public source"
    (public / ".git").mkdir(parents=True)
    sentinel = public / "docs" / "backtest-2026-06" / "distress_features.json"
    sentinel.parent.mkdir(parents=True)
    sentinel.write_text(CASE["sentinel"], encoding="utf-8")
    state["origins"][str(public)] = "https://github.com/example/synthetic-public.git"
    state["visibility"]["example/synthetic-public"] = visibility
    monkeypatch.setattr(research[0], "output_root", lambda: public / "reports" / "smallcap")
    monkeypatch.setattr(research[extractor], "ROOT", str(public))
    with pytest.raises(RuntimeError, match="PRIVATE|PUBLIC|visibility|verification"):
        (research[extractor].main if extractor == 0 else research[extractor].run)()
    assert sentinel.read_text(encoding="utf-8") == CASE["sentinel"]
    assert not (public / "reports").exists()


@pytest.mark.parametrize("extractor", [0, 1])
def test_uninitialized_research_writer_fails_before_pull(research, state, monkeypatch, extractor):
    from _common import ConfigNotInitialized

    (Path(state["companion"]) / "config.json").unlink()
    monkeypatch.setattr(research[extractor], "pull_one",
                        lambda *_: pytest.fail("uninitialized writer reached external work"))
    with pytest.raises(ConfigNotInitialized, match="UNINITIALIZED"):
        (research[extractor].main if extractor == 0 else research[extractor].run)()
    assert not Path(state["root"]).exists()


def test_each_research_checkpoint_reproves_destination(research, state):
    trusted = research[0]
    trusted.write_features([CASE["feature"]])
    destination = trusted.features_path()
    before = destination.read_bytes()
    state["visibility"]["example/synthetic-smallcap-config"] = "PUBLIC"
    with pytest.raises(RuntimeError, match="PRIVATE|PUBLIC"):
        trusted.write_features([])
    assert destination.read_bytes() == before


@pytest.mark.parametrize("rows", CASE["empty_features"])
def test_validation_empty_or_unusable_evidence_exits_nonzero(research, monkeypatch, rows, capsys):
    fast = research[1]
    monkeypatch.setattr(fast, "load_features", lambda: deepcopy(rows))
    monkeypatch.setattr(fast, "get_facts", lambda _: {})
    assert fast._cli(["validate"]) == 1
    output = capsys.readouterr().out
    assert "VALIDATION FAIL" in output and "0 nonempty comparisons" in output


def test_validation_missing_artifact_exits_nonzero(research, monkeypatch):
    def missing():
        raise FileNotFoundError("synthetic missing artifact")

    monkeypatch.setattr(research[1], "load_features", missing)
    assert research[1]._cli(["validate"]) == 1


@pytest.mark.parametrize("kind", ["match", "mismatch", "fetch_failure", "invalid"])
def test_validation_requires_observed_matching_values(research, monkeypatch, kind, capsys):
    fast = research[1]
    rows = CASE["invalid_features"] if kind == "invalid" else [CASE["feature"]]
    facts = deepcopy(CASE["facts"])
    if kind == "mismatch":
        facts["CashAndCashEquivalentsAtCarryingValue"]["units"]["USD"][0]["val"] += 1
    if kind == "fetch_failure":
        facts = {}
    monkeypatch.setattr(fast, "load_features", lambda: deepcopy(rows))
    monkeypatch.setattr(fast, "get_facts", lambda _: facts)
    assert fast._cli(["validate"]) == (0 if kind == "match" else 1)
    output = capsys.readouterr().out
    assert ("VALIDATION PASS" in output) is (kind == "match")
    if kind == "match":
        assert "1 nonempty comparisons" in output


def test_snapshot_commit_preserves_concurrent_append(tracker):
    first = deepcopy(CASE["quote"]["base_row"])
    second = {**first, "ticker": "SYNTHB"}
    tracker._save_verdicts([first])
    snapshot = tracker._load_verdicts()
    assert tracker._append_verdict(second) is True
    before = tracker.VERDICTS_FILE.read_bytes()
    snapshot[0]["scored"] = True
    with pytest.raises(RuntimeError, match="changed.*retry"):
        tracker._save_verdicts(snapshot)
    assert tracker.VERDICTS_FILE.read_bytes() == before
    assert tracker._load_verdicts() == [first, second]


def test_two_snapshot_updates_cannot_overwrite_each_other(tracker):
    tracker._save_verdicts([deepcopy(CASE["quote"]["base_row"])])
    first, second = tracker._load_verdicts(), tracker._load_verdicts()
    first[0]["score_unavailable_reason"] = "synthetic_first_update"
    second[0]["score_unavailable_reason"] = "synthetic_second_update"
    tracker._save_verdicts(first)
    before = tracker.VERDICTS_FILE.read_bytes()
    with pytest.raises(RuntimeError, match="changed.*retry"):
        tracker._save_verdicts(second)
    assert tracker.VERDICTS_FILE.read_bytes() == before
    assert tracker._load_verdicts() == first


def test_plain_list_cannot_overwrite_an_existing_ledger(tracker):
    tracker._save_verdicts([deepcopy(CASE["quote"]["base_row"])])
    before = tracker.VERDICTS_FILE.read_bytes()
    with pytest.raises(RuntimeError, match="snapshot"):
        tracker._save_verdicts([])
    assert tracker.VERDICTS_FILE.read_bytes() == before


def test_all_ledger_writers_share_exclusive_lock_and_retry(tracker):
    row = deepcopy(CASE["quote"]["base_row"])
    tracker._save_verdicts([row])
    snapshot = tracker._load_verdicts()
    target = tracker.VERDICTS_FILE
    before = target.read_bytes()
    with tracker._ledger_lock(target):
        for operation in (lambda: tracker._save_verdicts(snapshot),
                          lambda: tracker._append_verdict({**row, "ticker": "SYNTHB"})):
            with pytest.raises(RuntimeError, match="already in progress"):
                operation()
        assert target.read_bytes() == before
    assert tracker._append_verdict({**row, "ticker": "SYNTHB"}) is True
    assert tracker._append_verdict({**row, "ticker": "SYNTHB"}) is False
    assert len(tracker._load_verdicts()) == 2


@pytest.mark.parametrize("command", ["score", "backfill"])
def test_quote_work_allows_append_and_stale_commit_is_rejected(tracker, monkeypatch, command):
    quote = CASE["quote"]
    row = deepcopy(quote["base_row" if command == "score" else "missing_row"])
    second = {**row, "ticker": "SYNTHB"}
    tracker._save_verdicts([row])
    monkeypatch.setattr(tracker, "_today", lambda: quote["today"])
    calls = []

    def fetch(ticker, on_date, verbose=False):
        if not calls:
            assert tracker._append_verdict(second) is True
        calls.append((ticker, on_date))
        evidence = deepcopy(quote["entry_quotes"][ticker])
        evidence.update(requested_date=on_date, resolved_date=on_date)
        return evidence

    if command == "score":
        def fetch_snapshot(ticker, entry_date, horizon_date):
            from _forward_snapshot import snapshot_return
            entry = fetch(ticker, entry_date)
            snapshot = snapshot_return(ticker, entry_date, horizon_date, [
                [entry_date, entry["price"]],
                [horizon_date, entry["price"] * 1.1],
            ])
            assert snapshot["available"] is True
            return snapshot
        monkeypatch.setattr(tracker, "_fetch_return_snapshot", fetch_snapshot)
    else:
        monkeypatch.setattr(tracker, "_quote_on", fetch)
    with pytest.raises(RuntimeError, match="changed.*retry"):
        getattr(tracker, "cmd_" + command)(SimpleNamespace())
    assert calls
    assert tracker._load_verdicts() == [row, second]


@pytest.mark.parametrize("command", ["record", "backfill_validation_fp"])
def test_record_deduplicates_after_builder_interleaving(tracker, monkeypatch, command):
    row = deepcopy(CASE["quote"]["base_row"])

    def build(*_):
        assert tracker._append_verdict(row) is True
        return [deepcopy(row)]

    if command == "record":
        monkeypatch.setattr(tracker, "_build_verdict_from_flags", lambda args: build()[0])
        args = SimpleNamespace(record_path=None, ticker=row["ticker"])
    else:
        monkeypatch.setattr(tracker, "_build_validation_fp_rows", build)
        args = SimpleNamespace()
    getattr(tracker, "cmd_" + command)(args)
    assert tracker._load_verdicts() == [row]


@pytest.mark.parametrize("micro, expected", [(True, "watch"), (False, "deep")])
def test_selected_ceiling_survives_cheap_receipt_and_sic(state, monkeypatch, micro, expected):
    def unused_provider(*_args, **_kwargs):
        pytest.fail("mechanical ceiling case reached an unused provider")

    edgar = ModuleType("edgar")
    edgar.Company = unused_provider
    monkeypatch.setitem(sys.modules, "edgar", edgar)
    for name in ("_extract_concentration", "_concentration_flag"):
        monkeypatch.setattr(sys.modules["deepdive_data"], name, unused_provider, raising=False)
    # Record the prior missing/present state before forcing a fresh import.
    monkeypatch.setitem(sys.modules, "cheap_pass", None)
    monkeypatch.delitem(sys.modules, "cheap_pass", raising=False)
    import pandas as pd
    import filter_by_sic as stages
    import cheap_pass
    import run_theme

    root = Path(state["root"])
    for module in (run_theme, cheap_pass):
        monkeypatch.setattr(module, "REPORTS", root)
        monkeypatch.setattr(module, "CFG", deepcopy(CASE["config"]))
        monkeypatch.setattr(module, "today", lambda: CASE["asof"])
    monkeypatch.setattr(cheap_pass, "init_edgar", lambda: None)
    monkeypatch.setattr(cheap_pass, "health_check",
                        lambda row: {**row.to_dict(), **CASE["health"]})
    monkeypatch.setattr(cheap_pass, "score", lambda frame: frame)
    commands = []
    selected = CASE["config"]["micro_cap_max" if micro else "market_cap_max"]

    def run(command, label):
        commands.append(command)
        assert float(command[command.index("--max-mcap") + 1]) == selected
        if label == "DISCOVER":
            path = root / ("universe_" + CASE["slug"] + "_" + CASE["asof"] + ".csv")
            row = {**CASE["universe"][0], "band": expected}
            path.parent.mkdir(parents=True, exist_ok=True)
            pd.DataFrame([row]).to_csv(path, index=False)
            receipt = stages.stage_completion("synthetic_discover", 1,
                work=[stages.stage_work("synthetic_source")])
            stages.write_stage_receipt(path, receipt)
        else:
            assert label == "CHEAP_PASS"
            with monkeypatch.context() as nested:
                nested.setattr(sys, "argv", command[1:])
                assert cheap_pass.main() == 0

    monkeypatch.setattr(run_theme, "_run", run)
    argv = ["run_theme.py", "--theme", CASE["theme"], "--slug", CASE["slug"]]
    monkeypatch.setattr(sys, "argv", argv + (["--micro"] if micro else []))
    assert run_theme.main() == 0
    assert len(commands) == 2
    cheap = root / ("cheappass_" + CASE["slug"] + "_" + CASE["asof"] + ".csv")
    receipt = stages.read_stage_receipt(cheap, 1)
    assert receipt["decisions"][0]["band"] == expected
    candidates = root / ("candidates_" + CASE["slug"] + ".json")
    assert json.loads(candidates.read_text(encoding="utf-8"))[0]["band"] == expected


@pytest.mark.parametrize("status, count, limit, expected", [
    ("unavailable", 0, None, "unavailable"),
    ("complete", 0, None, "complete"),
    ("partial", 2, None, "partial"),
    ("complete", 2, 1, "partial"),
    ("complete", 2, None, "partial"),
])
def test_backtest_keeps_universe_completion_and_truncation(
        state, monkeypatch, status, count, limit, expected):
    import filter_by_sic as stages
    backtest = importlib.import_module("backtest")
    rows = stages.StageRows(deepcopy(CASE["universe"][:count]), stage="pit_universe",
        work=[stages.stage_work("synthetic_seed", status=status)],
        reasons=["historical_seed_coverage_unproved"] if status == "partial" else [])
    rows.completion.update(asof=CASE["asof"],
        coverage_scope="current_sic_seed_and_observed_submissions",
        identities=[{"cik": row["cik"], "ticker": row["ticker"]} for row in rows])
    monkeypatch.setattr(backtest, "_process_name",
        lambda row, *_: {**row, **deepcopy(CASE["processed"])})
    cell = backtest.run_cell(CASE["theme"], CASE["asof"], universe_fn=lambda *_: rows,
        benchmark_fn=lambda *_: deepcopy(CASE["benchmark"]), limit=limit)
    persisted = json.loads(Path(cell["output_path"]).read_text(encoding="utf-8"))
    assert persisted == {key: value for key, value in cell.items() if key != "output_path"}
    assert cell["universe_completion"] == rows.completion
    assert cell["completion"]["upstream"] == [rows.completion]
    assert cell["completion"]["status"] == expected
    assert ("historical_eligibility_unavailable" in cell["completion"]["reasons"]) is (count > 0)
    assert cell["universe_size_full"] == count
    assert cell["universe_size"] == cell["n_processed"] == (count if limit is None else min(count, limit))
    assert cell["truncated"] is (limit is not None and count > limit)
    assert ("universe_truncated" in cell["completion"]["reasons"]) is cell["truncated"]
    monkeypatch.setattr(backtest, "run_cell", lambda *_a, **_kw: cell)
    monkeypatch.setattr(sys, "argv", ["backtest.py", "--theme", CASE["theme"],
                                    "--asof", CASE["asof"], "--no-write"])
    assert backtest._cli() == (0 if expected == "complete" else 2)


def test_plain_universe_list_keeps_missing_completion_evidence(state):
    backtest = importlib.import_module("backtest")
    cell = backtest.run_cell(CASE["theme"], CASE["asof"], universe_fn=lambda *_: [],
        benchmark_fn=lambda *_: deepcopy(CASE["benchmark"]), write=False)
    assert cell["completion"]["status"] == "unavailable"
    assert "missing_completion_evidence" in cell["universe_completion"]["reasons"]
